apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: al5za04yl-python 
  janus-idp.io/tekton: al5za04yl-python
  backstage.io/kubernetes-id: al5za04yl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: al5za04yl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml