apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: al5za04yl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: al5za04yl-python 
  name: al5za04yl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: al5za04yl-python 
